#!/usr/bin/env python3

from hashlib import md5
from pprint import pprint
from sys import argv
from time import time
from uuid import uuid4

import requests

if len(argv) != 2:
    print(f'Usage: {argv[0]} <meross_device_ip>')
    exit(1)


def sign_packet(packet):
    """Return a signed version of the packet.
    """
    packet['header']['timestamp'] = int(time())
    packet['header']['messageId'] = uuid4().hex
    sign = (packet['header']['messageId'] + str(packet['header']['timestamp'])).encode('utf-8')
    packet['header']['sign'] = md5(sign).hexdigest()

    return packet

# Get the device info
device_information_json = {
    'header': {
        'method': 'GET',
        'namespace': 'Appliance.System.All',
    },
    'payload': {}
}
print(f'Requesting info from http://{argv[1]}/config.')
req = requests.post(f'http://{argv[1]}/config', json=sign_packet(device_information_json), timeout=60)
print('Response:', req.status_code)
pprint(req.json())
